# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "charmed-airflow-uats"
version = "3.1"
requires-python = ">=3.12"
description = "User acceptance tests for Charmed Airflow"
readme = "README.md"

[dependency-groups]
lint = [
	"ruff",
	"codespell",
]
format = [
	"ruff",
]
uat = [
	"pytest",
]


[tool.ruff]
target-version = "py312"
src = ["tests", "."]
line-length = 99


[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10

