# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = true
env_list = lint, uat, format

[testenv]
set_env = UV_PROJECT_ENVIRONMENT = {env_dir}

[testenv:lint]
description = check codestyle with ruff and codespell
allowlist_externals = uv
commands = 
    uv run --group lint ruff check .
    uv run --group lint codespell .

[testenv:format]
description = autoformat code with ruff
allowlist_externals = uv
commands =
    uv run --group format ruff check --fix .
    uv run --group format ruff format .

[testenv:uat]
description = run UAT tests
allowlist_externals = uv
commands =
    uv run --group uat pytest tests/
