# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = true
env_list = lint, uat, format

[vars]
tests_path = {tox_root}/tests
all_paths = {[vars]tests_path}
uv_flags = --isolated

[testenv]
set_env = UV_PROJECT_ENVIRONMENT = {env_dir}
allowlist_externals = uv

[testenv:lint]
description = check codestyle with ruff and codespell
deps =
    .[lint]
commands =
    uv sync --active --group lint
    uv run ruff check {[vars]all_paths}
    uv run codespell {[vars]all_paths}

[testenv:format]
description = autoformat code with ruff
commands =
    uv sync --active --group format
    uv run --group format ruff check --fix {[vars]all_paths}
    uv run --group format ruff format {[vars]all_paths}

[testenv:uats-identity]
description = Execute the UATs for the Airflow Identity integration
deps =
    .[uat]
commands =
    uv sync --active --group uat
    uv run {[vars]uv_flags} \
        pytest \
        {posargs} \
        {[vars]tests_path}/test_identity.py
